site_name: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_url: https://beardad1975.github.io/py4t/
site_description: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_author: Wen-Hung, Chang. å¼µæ–‡å®

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - é—œæ–¼: 
    - â¤ï¸ è¨ˆç•«ç·£ç”±: 'about/about.md'
    - ğŸ§¡ è¨­è¨ˆç†å¿µ: 'about/idea.md'
    - ğŸ’› è»Ÿé«”æ¶æ§‹: 'about/architecture.md'
    - ğŸ’š Q & A: 'about/qa.md'
    - ğŸ’™ æ„Ÿè¬: 'about/acknowledge.md'
  - ä¸‹è¼‰: 'download.md'
  - æµ·é¾œ: 
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - æµ·é¾œ: 'turtle4t/turtle4t.md'
    - ã€€ğŸ”° æ­£æ–¹å½¢ ç¯„ä¾‹: 'turtle4t/draw_square.md'
    - ã€€ğŸ”° æ­£å¤šé‚Šå½¢ ç¯„ä¾‹: 'turtle4t/regular_polygon.md'  
    - ã€€ğŸ”° èºæ—‹å½¢ ç¯„ä¾‹: 'turtle4t/spiral.md'
    - ã€€ğŸ”° ç¢å½¢æ¨¹ ç¯„ä¾‹: 'turtle4t/fractal_tree.md'

  - é‹ç®—æ€ç¶­:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - é‹ç®—æ€ç¶­: 'comthink/comthink.md'
    - ã€€ğŸ”° æ’åºæ’²å…‹ ç¯„ä¾‹: 'comthink/poker_sort.md'
    - ã€€ğŸ”° æœå°‹çŒœæ•¸ ç¯„ä¾‹: 'comthink/search_guess.md'

  - ç‰©ç†:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - ç‰©ç†: 'pie4t/pie4t.md'
    - ã€€ğŸ”° ç„¡æ‘©æ“¦åŠ› ç¯„ä¾‹: 'pie4t/frictionless.md'
    - ã€€ğŸ”° å°„æ“Šæ¸¬è©¦ ç¯„ä¾‹: 'pie4t/shoot.md'
    - ã€€ğŸ”° æ“æ§é‡åŠ› ç¯„ä¾‹: 'pie4t/gravity.md'
  - 3D:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - 3D: 'threed4t/threed4t.md'
    - ã€€ğŸ”° 3Dæ–¹å¡Š ç¯„ä¾‹: 'threed4t/first_3d.md'
    - ã€€ğŸ”° å½©è‰²æ–¹é™£ ç¯„ä¾‹: 'threed4t/color_array.md'
    - ã€€ğŸ”° å½©è‰²èºæ—‹ ç¯„ä¾‹: 'threed4t/color_spiral.md'

  - è¦–è¦º:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - è¦–è¦º: 'cv4t/cv4t.md'
    - ã€€ğŸ”° æ”å½±æ©Ÿ ç¯„ä¾‹: 'cv4t/camera.md'
    - ã€€ğŸ”° å½±åƒæ ¼ç·š ç¯„ä¾‹: 'cv4t/camera_slice.md'
    - ã€€ğŸ”° é›»è¦–ç‰† ç¯„ä¾‹: 'cv4t/camera_tile.md'

  - èªéŸ³:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - èªéŸ³èˆ‡è²éŸ³: 'sound_and_speech/sound_and_speech.md'
    - ã€€ğŸ”° æ–‡å­—è½‰èªéŸ³ ç¯„ä¾‹: 'sound_and_speech/tts.md'
    - ã€€ğŸ”° èªéŸ³è¾¨è­˜ ç¯„ä¾‹: 'sound_and_speech/speech_recog.md'  


theme:
  name: material
  custom_dir: overrides
  favicon: material/bridge
  icon:
    logo: material/bridge
    
  language: zh-TW
  palette:
    primary: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beardad1975
      name: beardad1975 on Github
    - icon: fontawesome/regular/envelope
      link: mailto:beardad1975@nmes.tyc.edu.tw
      name: beardad1975 email
    
      
copyright: Copyright &copy; 2021 Wen-Hung, Chang. å¼µæ–‡å®