site_name: Py4t-é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_url: https://beardad1975.github.io/py4t/
site_description: Py4t-é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_author: Wen-Hung, Chang. å¼µæ–‡å®

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - é¦–é : 'index.md'
  - ä¸‹è¼‰: 'download.md'
  - å­¸ç¿’æ¨¡çµ„: 
    - ğŸ“ æµ·é¾œå¹¾ä½•ç¹ªåœ–: 
      - ğŸ”° ç¯„ä¾‹ æ­£æ–¹å½¢: 'turtle4t/draw_square.md'
      - ğŸ”° ç¯„ä¾‹ æ­£å¤šé‚Šå½¢: 'turtle4t/regular_polygon.md'  

theme:
  name: material
  favicon: material/bridge
  icon:
    logo: material/bridge
    
  language: zh-TW
  palette:
    primary: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - toc.integrate
