site_name: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨

site_description: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_author: Wen-Hung, Chang. å¼µæ–‡å®

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



nav:
  - Home: 'index.md'
  - é—œæ–¼: 
    - â¤ï¸ è¨ˆç•«ç·£ç”±: 'about/plan.md'
    - ğŸ§¡ è¨­è¨ˆç†å¿µ: 'about/idea.md'
    - ğŸ’œ è»Ÿé«”æ¶æ§‹: 'about/architecture.md'
    - â¤ï¸ å•ç­”Q&A: 'about/qa.md'
    - ğŸ§¡ éŠ˜è¬: 'about/acknowledge.md'
  - ä¸‹è¼‰: 'download.md'
  - èª²ç¨‹: 
    - Py4tèª²ç¨‹: 'lesson/index.md'
    - æµ·é¾œç•«åœ‹æ——: 'lesson/national_flag/index.md'
    - åŠ›èˆ‡é‹å‹•éŠæ¨‚å ´: 'lesson/mechanics_playground/index.md'
  - æ¨å»£: 
    - ğŸ’š æ¨å»£ç´€éŒ„: 'promotion/activities.md'
    - ğŸ’™ ä½¿ç”¨å›é¥‹: 'promotion/user_feedback.md' 
    - ğŸ§¡ æ•™å­¸è³‡æ–™: 'promotion/teaching.md'
  - å½±ç‰‡: 
    - ğŸ“š å½±ç‰‡ç´¢å¼•: 'self_study/index.md'
    - ğŸ•’ å¿«é€Ÿå…¥é–€: 'self_study/quick_start.md'
    - ğŸ•• 3Dæ¨¡æ“¬: 'self_study/tutorial_3d.md'
    - ğŸ•˜ è¦–è¦ºå½±åƒ: 'self_study/tutorial_cv.md'
    - ğŸ•› æ¼”ç®—æ³•: 'self_study/tutorial_algorithm.md'
    
  - æµ·é¾œ: 
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - æµ·é¾œ: 'turtle4t/index.md'
    - ğŸ”° æ­£æ–¹å½¢ ç¯„ä¾‹: 'turtle4t/draw_square.md' 
    - ğŸ”° é•·æ–¹å½¢åŠå¡«è‰² ç¯„ä¾‹: 'turtle4t/rectangle_and_fill.md' 
    - ğŸ”° æ­£å¤šé‚Šå½¢ ç¯„ä¾‹: 'turtle4t/regular_polygon.md'  
    - ğŸ”° å¥‡æ•¸è§’æ˜Ÿå½¢ ç¯„ä¾‹: 'turtle4t/odd_number_star.md'
    - ğŸ”° æ³•åœ‹åœ‹æ—— ç¯„ä¾‹: 'turtle4t/flag_of_france.md'
    - ğŸ”° æ—¥æœ¬åœ‹æ—— ç¯„ä¾‹: 'turtle4t/flag_of_japan.md'
    - ğŸ”° è¶Šå—åœ‹æ—— ç¯„ä¾‹: 'turtle4t/flag_of_vietnam.md'
    - ğŸ”° ä¸­è¯æ°‘åœ‹åœ‹æ—— ç¯„ä¾‹: 'turtle4t/roc_flag.md'
    - ğŸ”° èºæ—‹å½¢ ç¯„ä¾‹: 'turtle4t/spiral.md'
    - ğŸ”° åœ“å½¢çºç¹ç•« ç¯„ä¾‹: 'turtle4t/circle_zentangle.md'
    - ğŸ”° ç¢å½¢æ¨¹ ç¯„ä¾‹: 'turtle4t/fractal_tree.md'

  - ç‰©ç†:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - ç‰©ç†: 'pie4t/index.md'
    - ğŸ”° ç„¡æ‘©æ“¦åŠ› ç¯„ä¾‹: 'pie4t/frictionless.md'
    - ğŸ”° å°„æ“Šæ¸¬è©¦ ç¯„ä¾‹: 'pie4t/shoot.md'
    - ğŸ”° æ“æ§é‡åŠ› ç¯„ä¾‹: 'pie4t/gravity.md'
    - ğŸ”° çƒçš„å½ˆæ€§ ç¯„ä¾‹: 'pie4t/bounce_ball.md'
    - ğŸ”° å½ˆæ€§æ’åˆ— ç¯„ä¾‹: 'pie4t/bounce_array.md'
    - ğŸ”° åŠ›èˆ‡æ–œé¢ ç¯„ä¾‹: 'pie4t/force_and_slide.md'
    - ğŸ”° æ…£æ€§èˆ‡é‡åŠ› ç¯„ä¾‹: 'pie4t/inertia_gravity.md'
  - 3D:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - 3D: 'threed4t/index.md'
    - ğŸ”° 3Dæ–¹å¡Š ç¯„ä¾‹: 'threed4t/first_3d.md'
    - ğŸ”° å½©è‰²æ–¹é™£ ç¯„ä¾‹: 'threed4t/color_array.md'
    - ğŸ”° å½©è‰²èºæ—‹ ç¯„ä¾‹: 'threed4t/color_spiral.md'
    - ğŸ”° å¤ªé™½ç³» ç¯„ä¾‹: 'threed4t/solar_system.md'

  - é‹ç®—æ€ç¶­:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - é‹ç®—æ€ç¶­: 'comthink/index.md'
    - ğŸ”° æ’åºæ’²å…‹ ç¯„ä¾‹: 'comthink/poker_sort.md'
    - ğŸ”° æœå°‹çŒœæ•¸ ç¯„ä¾‹: 'comthink/search_guess.md'

  - è¦–è¦º:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - è¦–è¦º: 'cv4t/index.md'
    - ğŸ”° æ”å½±æ©Ÿ ç¯„ä¾‹: 'cv4t/camera.md'
    - ğŸ”° å½±åƒæ ¼ç·š ç¯„ä¾‹: 'cv4t/camera_slice.md'
    - ğŸ”° é›»è¦–ç‰† ç¯„ä¾‹: 'cv4t/camera_tile.md'

  - èªéŸ³:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜ - èªéŸ³èˆ‡è²éŸ³: 'sound_and_speech/index.md'
    - ğŸ”° æ–‡å­—è½‰èªéŸ³ ç¯„ä¾‹: 'sound_and_speech/tts.md'
    - ğŸ”° èªéŸ³è¾¨è­˜ ç¯„ä¾‹: 'sound_and_speech/speech_recog.md'  


theme:
  name: material
  custom_dir: overrides
  favicon: material/bridge
  icon:
    logo: material/bridge
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    
  language: zh-TW
  palette:
    primary: indigo

  features:
    - navigation.tabs
    - navigation.sections
    
    - navigation.instant
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beardad1975
      name: beardad1975 on Github
    - icon: fontawesome/regular/envelope
      link: mailto:beardad1975@nmes.tyc.edu.tw
      name: beardad1975 email
    
      
copyright: Copyright &copy; 2022 Wen-Hung, Chang. å¼µæ–‡å®, æ¡ƒåœ’å¸‚æ¡ƒåœ’å€å—é–€åœ‹æ°‘å°å­¸æ•™å¸«