site_name: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_url: https://beardad1975.github.io/py4t/
site_description: Py4t - é’å°‘å¹´çš„Pythonç·¨è¼¯å™¨
site_author: Wen-Hung, Chang. å¼µæ–‡å®

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - é—œæ–¼: 'about.md'
  - ä¸‹è¼‰: 'download.md'
  - æµ·é¾œç¹ªåœ–: 
    - â“‚ï¸ æ¨¡çµ„èªªæ˜: 'turtle4t/turtle4t.md'
    - ã€€ğŸ”° æ­£æ–¹å½¢ ç¯„ä¾‹: 'turtle4t/draw_square.md'
    - ã€€ğŸ”° æ­£å¤šé‚Šå½¢ ç¯„ä¾‹: 'turtle4t/regular_polygon.md'  
    - ã€€ğŸ”° èºæ—‹å½¢ ç¯„ä¾‹: 'turtle4t/spiral.md'
    - ã€€ğŸ”° ç¢å½¢æ¨¹ ç¯„ä¾‹: 'turtle4t/fractal_tree.md'
  - ç‰©ç†ç¢°æ’:
    - â“‚ï¸ æ¨¡çµ„èªªæ˜: 'pie4t/pie4t.md'
    - ã€€ğŸ”° ç„¡æ‘©æ“¦åŠ› ç¯„ä¾‹: 'pie4t/frictionless.md'
    - ã€€ğŸ”° å°„æ“Šæ¸¬è©¦ ç¯„ä¾‹: 'pie4t/shoot.md'
    - ã€€ğŸ”° æ“æ§é‡åŠ› ç¯„ä¾‹: 'pie4t/gravity.md'


theme:
  name: material
  favicon: material/bridge
  icon:
    logo: material/bridge
    
  language: zh-TW
  palette:
    primary: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beardad1975
      name: beardad1975 on Github
    - icon: fontawesome/regular/envelope
      link: mailto:beardad1975@nmes.tyc.edu.tw
      name: beardad1975 email
    
      
copyright: Copyright &copy; 2021 Wen-Hung, Chang. å¼µæ–‡å®