site_name: Py4t æ•™é’å°‘å¹´å­¸Python

site_description: Py4t æ•™é’å°‘å¹´å­¸Python
site_author: Wen-Hung, Chang. å¼µæ–‡å®

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.tabbed:
      alternate_style: true 



nav:
  - Home: 'index.md'
  - é—œæ–¼: 
    - â¤ï¸ è¨ˆç•«ç·£ç”±: 'about/plan.md'
    - ğŸ§¡ è¨­è¨ˆç†å¿µ: 'about/idea.md'
    - ğŸ’œ è»Ÿé«”æ¶æ§‹: 'about/architecture.md'
    - â¤ï¸ å•ç­”Q&A: 'about/qa.md'
    - ğŸ§¡ éŠ˜è¬: 'about/acknowledge.md'
  - ä¸‹è¼‰: 'download.md'
  - èª²ç¨‹: 
    - Py4tèª²ç¨‹: 'lesson/index.md'

  - å‡½å¼åº«: 
    - ç´¢å¼•é : 'integrated_lib.md' 
    - æµ·é¾œ: 
      - ğŸ¢ æµ·é¾œ æ•™å­¸å‡½å¼åº«: 'turtle4t/index.md'


    - ç‰©ç†:
      - ğŸ€ ç‰©ç† æ•™å­¸å‡½å¼åº«: 'pie4t/index.md'

    - 3D:
      - ğŸ§Š 3D æ•™å­¸å‡½å¼åº«: 'threed4t/index.md'


    - é‹ç®—æ€ç¶­:
      - â° æ¨¡çµ„èªªæ˜ - é‹ç®—æ€ç¶­: 'comthink/index.md'


    - è¦–è¦º:
      - ğŸ‘ï¸â€ğŸ—¨ï¸ æ¨¡çµ„èªªæ˜ - è¦–è¦º: 'cv4t/index.md'


    - èªéŸ³:
      - ğŸ‘„ æ¨¡çµ„èªªæ˜ - èªéŸ³èˆ‡è²éŸ³: 'sound_and_speech/index.md'

  - å½±ç‰‡: 
    - ğŸ“š å½±ç‰‡ç´¢å¼•: 'self_study/index.md'
    - ğŸ•’ å¿«é€Ÿå…¥é–€: 'self_study/quick_start.md'
    - ğŸ•• 3Dæ¨¡æ“¬: 'self_study/tutorial_3d.md'
    - ğŸ•˜ è¦–è¦ºå½±åƒ: 'self_study/tutorial_cv.md'
    - ğŸ•› æ¼”ç®—æ³•: 'self_study/tutorial_algorithm.md'
  - æ¨å»£: 
    - ğŸ’š æ¨å»£ç´€éŒ„: 'promotion/activities.md'
    - ğŸ’™ ä½¿ç”¨å›é¥‹: 'promotion/user_feedback.md' 
    - ğŸ§¡ æ•™å­¸è³‡æ–™: 'promotion/teaching.md'
  - ç¤¾ç¾¤: 
    - ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ fbç¤¾åœ˜èˆ‡Py4tç·´åŠŸåŠ: 'community/society.md'
    - ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ [è¨è«–]åç¨±æ›´æ”¹: 'community/name_change.md'
    - ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ [å•ç­”]Py4tç¶²ç«™è£½ä½œ: 'community/website_howto.md'
    - ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ [å•ç­”]æ¶æ§‹èˆ‡åŸå§‹ç¢¼å°è¦½: 'community/source_guide.md'

theme:
  name: material
  custom_dir: overrides
  favicon: material/bridge
  icon:
    logo: material/bridge
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    
  language: zh-TW
  palette:
    primary: indigo

  features:
    - navigation.tabs
    - navigation.sections
    
    - navigation.instant
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beardad1975
      name: beardad1975 on Github
    - icon: fontawesome/regular/envelope
      link: mailto:beardad1975@nmes.tyc.edu.tw
      name: beardad1975 email
    
      
copyright: Copyright &copy; 2022 Wen-Hung, Chang å¼µæ–‡å®.